## Numpy with Sheryians AI Coding School

In [3]:
import numpy as np

### 1. Array Creation

In [2]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [5]:
my_list = [6,7,8,9,10]
print(f"My List: {my_list}")
print(f"The type of my_list is {type(my_list)}")
print("Now converting my_list to a numpy array...")
my_arr = np.array(my_list)
print(f"My Numpy Array: {my_arr}")
print(f"The type of my_array is {type(my_arr)}")

My List: [6, 7, 8, 9, 10]
The type of my_list is <class 'list'>
Now converting my_list to a numpy array...
My Numpy Array: [ 6  7  8  9 10]
The type of my_array is <class 'numpy.ndarray'>


In [10]:
person = ["Sulaiman", 19, "Data Analyst"]
print(f"My Person List: {person}")
print(f"The type of person is {type(person)}")
print(type(person[1]))


print("Now converting person to a numpy array...")
person_arr = np.array(person)
print(f"Person Array has values: {person_arr}")
print(f"The type of person_arr is {type(person_arr)}")


"""
So from this we can see that the list can contain different data types, 
but when we convert it to a numpy array, it will convert all the elements 
to the same data type (which have precedence like strings over integers, or float over integers). 
In this case, it converted all the elements to strings."""


My Person List: ['Sulaiman', 19, 'Data Analyst']
The type of person is <class 'list'>
<class 'int'>
Now converting person to a numpy array...
Person Array has values: ['Sulaiman' '19' 'Data Analyst']
The type of person_arr is <class 'numpy.ndarray'>


'\nSo from this we can see that the list can contain different data types, \nbut when we convert it to a numpy array, it will convert all the elements \nto the same data type (which have precedence like strings over integers, or float over integers). \nIn this case, it converted all the elements to strings.'

In [5]:
# So above we're converting a list into 1D, here we'll be doing same for 2D arrays.

numbers = [[1,2,3], [4,5,6], [7,8,9]]
print(f"My List: {numbers}")
print(f"The type of numbers List is {type(numbers)}")

print("\nNow converting numbers to a numpy array...")
numbers_arr = np.array(numbers)
print(f"My Numpy Array:\n {numbers_arr}")

My List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
The type of numbers List is <class 'list'>

Now converting numbers to a numpy array...
My Numpy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# For creating an array we can use the arange function(to which we call range)
np.arange(0, 11) # this will create an array from 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Creating 1D array of zeros
np.zeros(5) # this will create an array of 5 zeros

array([0., 0., 0., 0., 0.])

In [10]:
# Creating a 2D array (matrix) of zeros
np.zeros((3,4)) # This means 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Linear Spacing (linspace) is a function used for equal intervals between numbers when we want
arr_10 = np.linspace(1,10, 5)
print(arr_10) #Now what does this mean, it means that there is equal numbers between 1 to 3.25 and 5.5 and rest

[ 1.    3.25  5.5   7.75 10.  ]


#### Attributes of Numpy Arrays

In [15]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"Array:\n {array}")
print(f"Shape of the array: {array.shape}")
# Or
print(array.shape)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)
(3, 3)


In [16]:
array.size # this will give us the total number of elements in the array, which is 9 in this case (3 rows * 3 columns)

9

In [17]:
array.dtype # this will give us the data type of the elements in the array, which is int64 in this case (integers)

dtype('int64')

### Array Methods

In [20]:
print("Minimum Number", array.min()) # this will give us the minimum value in the array, which is 1 in this case
print("Maximum Number", array.max()) # this will give us the maximum value in the array, which is 9 in this case
print("Sum of all elements", array.sum()) # this will give us the sum of all the elements in the array, which is 45 in this case
print("Mean of all elements", array.mean()) # this will give us the mean (average) of the elements in the array, which is 5 in this case
print("Standard Deviation", array.std()) # this will give us the standard deviation of the elements in the array,

Minimum Number 1
Maximum Number 9
Sum of all elements 45
Mean of all elements 5.0
Standard Deviation 2.581988897471611


In [24]:
np.sum(array) # this will also give us the sum of all the elements in the array, which is 45 in this case
np.sum(array, axis=0) # this will give us the sum of each column in the array, which is [12, 15, 18] in this case
np.sum(array, axis=1) # this will give us the sum of each row in the array, which is [6, 15, 24] in this case

# Now printing all these
print("Sum of all elements", np.sum(array)) # this will give us the sum of all the elements in the array, which is 45 in this case
print("Sum of each column", np.sum(array, axis=0)) # this will give us the sum of each column in the array, which is [12, 15, 18] in this case
print("Sum of each row", np.sum(array, axis=1)) # this will give us the sum of each row in the array, which is [6, 15, 24] in this case

Sum of all elements 45
Sum of each column [12 15 18]
Sum of each row [ 6 15 24]


#### Reshaping and Resizing Arrays

In [31]:
my_array = np.arange(1, 31) # this will create an array from 1 to 30
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [34]:
reshaped_array = my_array.reshape(6,5) # this will reshape the array into 6 rows and 5 columns, but it will not change the original array
print(reshaped_array) # this will print the reshaped array, which is now 2D with 6 rows and 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
