In [12]:
import numpy as np

#### 1. Numpy Indexing and Slicing of Vectors (1D Arrays)

In [13]:
my_array = np.arange(10,21)
print(my_array)
print(type(my_array))

[10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


In [14]:
# Indexing

# Indexing means accessing individual elements of the array using their index. 
# In Python, indexing starts from 0, so the first element of the array is at index 0, 
# the second element is at index 1, and so on.

print(my_array[0]) # the first element
print(my_array[5]) # the sixth element
print(my_array[-1]) # the last element & when we put - sign, we start from last element & move towords first element
print(my_array[-2]) # the second last element



10
15
20
19


In [15]:
# Slicing

# Slicing means accessing a range of elements in the array using a start index, an end index, and an optional step.
# The syntax for slicing is array[start:end:step], where start is the index of the first element to include, 
# end is the index of the first element to exclude, and step is the number of indices to skip between elements.

print(f"first 5 elements: {my_array[0:5]}" ) # this will give us the first 5 elements of the array, which are [10, 11, 12, 13, 14]
print(f"elements from index 6 to end of array: {my_array[6:]}" ) # this will give us all the elements from index 6
print(f"elements with step size 2: {my_array[::2]}" ) # this will give us all the elements from the start of the array to index 4

first 5 elements: [10 11 12 13 14]
elements from index 6 to end of array: [16 17 18 19 20]
elements with step size 2: [10 12 14 16 18 20]


#### 2. Indexing and Slicing in 2D Arrays

In [16]:
my_array = np.arange(1,31).reshape(6,5)
print(my_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [26]:
print(f"My List:\n {my_array}")

# Accessing rows in 2D array
print(f"\nFirst row: {my_array[0]}") # this will give us the element at the first row
print(f"Second row: {my_array[1]}") # this will give us the element at the second row
print(f"Last row: {my_array[-1]} -1 Method") # this will give us the element at the last row
# OR
print(f"Last row: {my_array[5]} Simple Method") # this will also give us the element at the last row, which is [26, 27, 28, 29, 30]

# Accessing specific element in 2D array
print(f"\nElement at row 1, column 2: {my_array[0,1]}") # this will give us the element at row 1 and column 2, which is 2 in this case
print(f"Element at row 3, column 4: {my_array[2,3]}") # this will give us the element at row 3 and column 4, which is 14 in this case

My List:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

First row: [1 2 3 4 5]
Second row: [ 6  7  8  9 10]
Last row: [26 27 28 29 30] -1 Method
Last row: [26 27 28 29 30] Simple Method

Element at row 1, column 2: 2
Element at row 3, column 4: 14


In [31]:
# Printing a perticular column in 2D array
print(my_array[:, 0])

[ 1  6 11 16 21 26]


In [32]:
# Slicing a perticular part of 2D array
print(my_array[1:4, 2:5]) # this will give us the

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [33]:
print(my_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [37]:
slice = my_array[3:,3:] # Putting nothing after : as we want till end
print(slice)

[[19 20]
 [24 25]
 [29 30]]
