#### Array Operations

In [1]:
import numpy as np

In [ ]:
# Adding two Arrays

# For doing this the array shape & size should be same
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(f"Sum of Array a1 {a1} and Array a2 {a2} is {a1 + a2}")

Sum of Array a1 [1 2 3 4 5] and Array a2 [ 6  7  8  9 10] is [ 7  9 11 13 15]


In [4]:
# Subtracting two Arrays
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
# Multiplying two Arrays
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
# Dividing two Arrays
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
# Floor Division
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [ ]:
# Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes during 
# arithmetic operations. It automatically expands the smaller array to match the shape of the larger array, 
# enabling element-wise operations without the need for explicit loops.

my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_list + 10 # To add 10 to each element of the list we need to use list comprehension or a loop so instead of this we should use numpy array which supports broadcasting
my_array + 10   

array([11, 12, 13, 14, 15])

**Deep and Shallow Copy** Shallow copy means to copy something and do some operations and the original is not affected and there is an another copy of original data which is stored in an another address

In [12]:
my_array = np.arange(1,21)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
arr_slice = my_array[:5]
print(f"Original Sliced Array:{arr_slice}\n")
arr_slice = arr_slice * 2
print(f"Array after Multiplication with 2:{arr_slice}\n")

Original Sliced Array:[1 2 3 4 5]

Array after Multiplication with 2:[ 2  4  6  8 10]



#### Matrix Operations

In [14]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)

In [15]:
print(f"Array A:\n{A}\n")
print(f"Array B:\n{B}\n")

Array A:
[[1 2]
 [3 4]]

Array B:
[[5 6]
 [7 8]]



In [19]:
# Multiplication
A @ B
A * B # Element-wise multiplication and doesn't represent the dot product of A and B
print(f"Dot Product of A and B is:\n{A @ B}\n")
print(f"Element-wise Product of A and B is:\n{A * B}\n")

Dot Product of A and B is:
[[19 22]
 [43 50]]

Element-wise Product of A and B is:
[[ 5 12]
 [21 32]]



In [21]:
# Another method of doing dot product is using np.dot() function
np.dot(A,B)
print(f"Dot Product of A and B using np.dot() function is:\n{np.dot(A,B)}\n")

Dot Product of A and B using np.dot() function is:
[[19 22]
 [43 50]]



In [22]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation

In [23]:
# Splitting the array
c = np.arange(16).reshape(4,4)
print(f"Simple Array of 4 by 4:\n {c}\n")

Simple Array of 4 by 4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



In [24]:
splited = np.hsplit(c,2) # c is the array and 2 are the parts in which we want to split this array
print(f"Array after spliting:\nSplit 1\n {splited[0]},\nSplit 2\n {splited[1]}\n")

Array after spliting:
Split 1
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]],
Split 2
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

