#### Array Operations

In [1]:
import numpy as np

In [ ]:
# Adding two Arrays

# For doing this the array shape & size should be same
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(f"Sum of Array a1 {a1} and Array a2 {a2} is {a1 + a2}")

Sum of Array a1 [1 2 3 4 5] and Array a2 [ 6  7  8  9 10] is [ 7  9 11 13 15]


In [4]:
# Subtracting two Arrays
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
# Multiplying two Arrays
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
# Dividing two Arrays
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
# Floor Division
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [ ]:
# Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes during 
# arithmetic operations. It automatically expands the smaller array to match the shape of the larger array, 
# enabling element-wise operations without the need for explicit loops.

my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_list + 10 # To add 10 to each element of the list we need to use list comprehension or a loop so instead of this we should use numpy array which supports broadcasting
my_array + 10   

array([11, 12, 13, 14, 15])

**Deep and Shallow Copy** Shallow copy means to copy something and do some operations and the original is not affected and there is an another copy of original data which is stored in an another address

In [12]:
my_array = np.arange(1,21)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
arr_slice = my_array[:5]
print(f"Original Sliced Array:{arr_slice}\n")
arr_slice = arr_slice * 2
print(f"Array after Multiplication with 2:{arr_slice}\n")

Original Sliced Array:[1 2 3 4 5]

Array after Multiplication with 2:[ 2  4  6  8 10]

