#### Array Operations

In [1]:
import numpy as np

In [ ]:
# Adding two Arrays

# For doing this the array shape & size should be same
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(f"Sum of Array a1 {a1} and Array a2 {a2} is {a1 + a2}")

Sum of Array a1 [1 2 3 4 5] and Array a2 [ 6  7  8  9 10] is [ 7  9 11 13 15]


In [4]:
# Subtracting two Arrays
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
# Multiplying two Arrays
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
# Dividing two Arrays
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
# Floor Division
a1 // a2

array([0, 0, 0, 0, 0])