In [3]:
import numpy as np

**Valid Sudoku**

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
np.sum(s[:,0])

np.int64(45)

In [21]:
np.sum(s, axis=0) # Sum of each column
np.sum(s, axis=1) # Sum of each row

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [20]:
print(f"Sum of each column:\n{np.sum(s, axis=0)}\n")
print(f"Sum of each row:\n{np.sum(s, axis=1)}\n")

Sum of each column:
[45 45 45 45 45 45 45 45 45]

Sum of each row:
[45 45 45 45 45 45 45 45 45]



**General Questions**

In [5]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [22]:
#Get the shape of the matrix.
np.shape(data)


(5, 3)

In [23]:
#Find the average age of students.
print(f"Average of ages: {np.mean(data[:,0])}\n")


Average of ages: 18.4



In [24]:
#Extract Math marks of all students.
print(f"Math marks: {data[:,1]}\n")

Math marks: [85 92 76 65 90]



In [26]:
#Find the highest Science mark.
print(f"Highest Science mark (Method 1): {data.max(axis=0)[2]} ")
print(f"Highest Science mark (Method 2): {data[:,2].max()} ")

Highest Science mark (Method 1): 95 
Highest Science mark (Method 2): 95 


In [27]:
#Get details of the student who scored more than 90 in Math.

print(f"Details of students who scored more than 90 in Math:\n{data[data[:,1] > 90]}")

Details of students who scored more than 90 in Math:
[[19 92 88]]


In [ ]:
#Increase Math marks of all students by 5.



In [12]:
#Find how many students are younger than 19.


In [13]:
#Calculate the average marks in each subject (column-wise mean).


In [14]:
#Get data of students who scored at least 80 in both subjects.


In [15]:
#Replace all Science marks < 75 with 0.
